version: "3.4"

services:
  db:
    container_name: mini-otl-server-db
    image: mysql:5.7
    restart: on-failure
    ports:
      - '${MINI_OTL_DB_PORT:-43306}:3306'
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=miniotl
      - TZ=Asia/Seoul
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/dump
    command: |
      --sql_mode=NO_ENGINE_SUBSTITUTION --default_storage_engine=InnoDB 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci